-- Insert 150 sample products with full image URLs and varied discounts
INSERT INTO products (name, rating, number_of_ratings, category, type, price, discount, image) VALUES
('Samsung 55" LED TV', 4.5, 120, 'Electronics', 'Televisions', 599.99, 0.1, 'https://example.com/images/samsung_tv.jpg'),
('Levi''s Men''s Jeans', 4.2, 85, 'Fashion', 'Men''s Clothing', 49.99, 0.15, 'https://example.com/images/levis_jeans.jpg'),
('Instant Pot Pressure Cooker', 4.8, 200, 'Appliances', 'Kitchen Appliances', 89.99, 0.2, 'https://example.com/images/instant_pot.jpg'),
('Apple MacBook Air', 4.7, 150, 'Computing', 'Laptops', 999.99, 0, 'https://example.com/images/macbook_air.jpg'),
('L''Oreal Shampoo', 4.3, 95, 'Health and Beauty', 'Hair Care', 12.99, 0.1, 'https://example.com/images/loreal_shampoo.jpg'),
('Nike Running Shoes', 4.6, 110, 'Sporting Goods', 'Footwear', 79.99, 0.2, 'https://example.com/images/nike_shoes.jpg'),
('Pampers Diapers', 4.4, 75, 'Baby Products', 'Diapers', 29.99, 0, 'https://example.com/images/pampers.jpg'),
('PlayStation 5', 4.9, 300, 'Gaming', 'Consoles', 499.99, 0, 'https://example.com/images/ps5.jpg'),
('Ikea Office Chair', 4.1, 65, 'Home & Office', 'Furniture', 129.99, 0.15, 'https://example.com/images/ikea_chair.jpg'),
('Heinz Ketchup', 4.0, 50, 'Supermarket', 'Condiments', 3.99, 0, 'https://example.com/images/heinz_ketchup.jpg'),
('Bose Wireless Headphones', 4.7, 180, 'Electronics', 'Audio', 199.99, 0.1, 'https://example.com/images/bose_headphones.jpg'),
('Adidas Track Pants', 4.3, 90, 'Fashion', 'Sportswear', 39.99, 0.2, 'https://example.com/images/adidas_pants.jpg'),
('Dyson Vacuum Cleaner', 4.6, 140, 'Appliances', 'Cleaning', 299.99, 0.15, 'https://example.com/images/dyson_vacuum.jpg'),
('Dell XPS Desktop', 4.5, 100, 'Computing', 'Desktops', 799.99, 0, 'https://example.com/images/dell_xps.jpg'),
('Neutrogena Face Cream', 4.4, 80, 'Health and Beauty', 'Skincare', 14.99, 0.1, 'https://example.com/images/neutrogena_cream.jpg'),
('Wilson Basketball', 4.2, 60, 'Sporting Goods', 'Sports Equipment', 24.99, 0, 'https://example.com/images/wilson_basketball.jpg'),
('Huggies Baby Wipes', 4.3, 70, 'Baby Products', 'Baby Care', 9.99, 0.1, 'https://example.com/images/huggies_wipes.jpg'),
('Nintendo Switch', 4.8, 250, 'Gaming', 'Consoles', 299.99, 0, 'https://example.com/images/nintendo_switch.jpg'),
('West Elm Sofa', 4.4, 55, 'Home & Office', 'Furniture', 899.99, 0.2, 'https://example.com/images/westelm_sofa.jpg'),
('Kellogg''s Corn Flakes', 4.0, 45, 'Supermarket', 'Cereal', 4.99, 0, 'https://example.com/images/kelloggs_cereal.jpg'),
('Sony 65" OLED TV', 4.8, 130, 'Electronics', 'Televisions', 1499.99, 0.1, 'https://example.com/images/sony_oled.jpg'),
('Zara Women''s Dress', 4.3, 75, 'Fashion', 'Women''s Clothing', 59.99, 0.15, 'https://example.com/images/zara_dress.jpg'),
('Ninja Air Fryer', 4.6, 160, 'Appliances', 'Kitchen Appliances', 119.99, 0.2, 'https://example.com/images/ninja_airfryer.jpg'),
('HP Pavilion Laptop', 4.4, 90, 'Computing', 'Laptops', 649.99, 0, 'https://example.com/images/hp_pavilion.jpg'),
('Olay Body Lotion', 4.2, 65, 'Health and Beauty', 'Skincare', 8.99, 0.1, 'https://example.com/images/olay_lotion.jpg'),
('Spalding Soccer Ball', 4.1, 50, 'Sporting Goods', 'Sports Equipment', 19.99, 0, 'https://example.com/images/spalding_soccer.jpg'),
('Johnson''s Baby Shampoo', 4.5, 80, 'Baby Products', 'Baby Care', 6.99, 0.1, 'https://example.com/images/johnsons_shampoo.jpg'),
('Xbox Series X', 4.8, 280, 'Gaming', 'Consoles', 499.99, 0, 'https://example.com/images/xbox_seriesx.jpg'),
('Ashley Dining Table', 4.3, 60, 'Home & Office', 'Furniture', 499.99, 0.15, 'https://example.com/images/ashley_table.jpg'),
('Coca-Cola 12-Pack', 4.2, 55, 'Supermarket', 'Beverages', 5.99, 0, 'https://example.com/images/coca_cola.jpg'),
('LG 32" Monitor', 4.5, 100, 'Electronics', 'Monitors', 199.99, 0.1, 'https://example.com/images/lg_monitor.jpg'),
('H&M T-Shirt', 4.0, 70, 'Fashion', 'Men''s Clothing', 14.99, 0.2, 'https://example.com/images/hm_tshirt.jpg'),
('KitchenAid Mixer', 4.7, 120, 'Appliances', 'Kitchen Appliances', 349.99, 0.15, 'https://example.com/images/kitchenaid_mixer.jpg'),
('Lenovo ThinkPad', 4.6, 110, 'Computing', 'Laptops', 899.99, 0, 'https://example.com/images/lenovo_thinkpad.jpg'),
('CeraVe Cleanser', 4.5, 85, 'Health and Beauty', 'Skincare', 12.99, 0.1, 'https://example.com/images/cerave_cleanser.jpg'),
('Under Armour Gym Bag', 4.3, 60, 'Sporting Goods', 'Accessories', 34.99, 0, 'https://example.com/images/underarmour_bag.jpg'),
('Enfamil Formula', 4.4, 75, 'Baby Products', 'Baby Food', 24.99, 0.05, 'https://example.com/images/enfamil_formula.jpg'),
('Logitech Gaming Mouse', 4.6, 90, 'Gaming', 'Accessories', 49.99, 0.1, 'https://example.com/images/logitech_mouse.jpg'),
('CB2 Bookshelf', 4.2, 50, 'Home & Office', 'Furniture', 299.99, 0.15, 'https://example.com/images/cb2_bookshelf.jpg'),
('Quaker Oats', 4.1, 40, 'Supermarket', 'Cereal', 3.99, 0, 'https://example.com/images/quaker_oats.jpg'),
('JBL Bluetooth Speaker', 4.5, 110, 'Electronics', 'Audio', 89.99, 0.2, 'https://example.com/images/jbl_speaker.jpg'),
('Forever 21 Jacket', 4.0, 65, 'Fashion', 'Women''s Clothing', 39.99, 0.15, 'https://example.com/images/forever21_jacket.jpg'),
('Breville Toaster Oven', 4.6, 100, 'Appliances', 'Kitchen Appliances', 149.99, 0.1, 'https://example.com/images/breville_oven.jpg'),
('Acer Monitor', 4.3, 80, 'Computing', 'Monitors', 129.99, 0, 'https://example.com/images/acer_monitor.jpg'),
('Dove Soap', 4.2, 70, 'Health and Beauty', 'Personal Care', 4.99, 0.05, 'https://example.com/images/dove_soap.jpg'),
('Adidas Yoga Mat', 4.4, 60, 'Sporting Goods', 'Fitness', 29.99, 0.1, 'https://example.com/images/adidas_yogamat.jpg'),
('Gerber Baby Food', 4.3, 65, 'Baby Products', 'Baby Food', 2.99, 0, 'https://example.com/images/gerber_food.jpg'),
('Razer Gaming Keyboard', 4.7, 120, 'Gaming', 'Accessories', 99.99, 0.1, 'https://example.com/images/razer_keyboard.jpg'),
('Pottery Barn Lamp', 4.2, 50, 'Home & Office', 'Lighting', 79.99, 0.15, 'https://example.com/images/potterybarn_lamp.jpg'),
('Pepsi 12-Pack', 4.1, 55, 'Supermarket', 'Beverages', 5.99, 0, 'https://example.com/images/pepsi.jpg'),
('Canon DSLR Camera', 4.6, 130, 'Electronics', 'Cameras', 599.99, 0.1, 'https://example.com/images/canon_dslr.jpg'),
('Mango Women''s Skirt', 4.0, 60, 'Fashion', 'Women''s Clothing', 29.99, 0.2, 'https://example.com/images/mango_skirt.jpg'),
('Cuisinart Coffee Maker', 4.5, 90, 'Appliances', 'Kitchen Appliances', 79.99, 0, 'https://example.com/images/cuisinart_coffee.jpg'),
('Asus ROG Laptop', 4.7, 140, 'Computing', 'Gaming Laptops', 1299.99, 0.1, 'https://example.com/images/asus_rog.jpg'),
('Clinique Moisturizer', 4.4, 75, 'Health and Beauty', 'Skincare', 29.99, 0.1, 'https://example.com/images/clinique_moisturizer.jpg'),
('Reebok Dumbbells', 4.3, 65, 'Sporting Goods', 'Fitness', 49.99, 0, 'https://example.com/images/reebok_dumbbells.jpg'),
('Similac Formula', 4.5, 80, 'Baby Products', 'Baby Food', 27.99, 0.05, 'https://example.com/images/similac_formula.jpg'),
('SteelSeries Headset', 4.6, 100, 'Gaming', 'Accessories', 79.99, 0.1, 'https://example.com/images/steelseries_headset.jpg'),
('Crate & Barrel Rug', 4.2, 55, 'Home & Office', 'Decor', 199.99, 0.15, 'https://example.com/images/crate_barrel_rug.jpg'),
('Nestlé Coffee', 4.1, 50, 'Supermarket', 'Beverages', 7.99, 0, 'https://example.com/images/nestle_coffee.jpg'),
('Samsung Galaxy Phone', 4.7, 200, 'Electronics', 'Smartphones', 799.99, 0.1, 'https://example.com/images/samsung_galaxy.jpg'),
('Uniqlo Sweater', 4.3, 70, 'Fashion', 'Men''s Clothing', 34.99, 0.15, 'https://example.com/images/uniqlo_sweater.jpg'),
('Philips Air Purifier', 4.5, 85, 'Appliances', 'Home Appliances', 199.99, 0, 'https://example.com/images/philips_purifier.jpg'),
('MSI Gaming Monitor', 4.6, 110, 'Computing', 'Monitors', 249.99, 0.1, 'https://example.com/images/msi_monitor.jpg'),
('Nivea Body Wash', 4.2, 60, 'Health and Beauty', 'Personal Care', 5.99, 0.05, 'https://example.com/images/nivea_bodywash.jpg'),
('Nike Soccer Cleats', 4.4, 75, 'Sporting Goods', 'Footwear', 59.99, 0.1, 'https://example.com/images/nike_cleats.jpg'),
('Luvs Diapers', 4.3, 65, 'Baby Products', 'Diapers', 19.99, 0, 'https://example.com/images/luvs_diapers.jpg'),
('HyperX Mouse Pad', 4.5, 80, 'Gaming', 'Accessories', 19.99, 0.05, 'https://example.com/images/hyperx_mousepad.jpg'),
('Wayfair Desk', 4.2, 50, 'Home & Office', 'Furniture', 149.99, 0.15, 'https://example.com/images/wayfair_desk.jpg'),
('Lipton Tea', 4.1, 45, 'Supermarket', 'Beverages', 4.99, 0, 'https://example.com/images/lipton_tea.jpg'),
('Apple AirPods', 4.7, 250, 'Electronics', 'Audio', 149.99, 0.1, 'https://example.com/images/airpods.jpg'),
('Gap Hoodie', 4.3, 80, 'Fashion', 'Men''s Clothing', 44.99, 0.2, 'https://example.com/images/gap_hoodie.jpg'),
('Hamilton Blender', 4.4, 70, 'Appliances', 'Kitchen Appliances', 39.99, 0, 'https://example.com/images/hamilton_blender.jpg'),
('Samsung SSD', 4.6, 100, 'Computing', 'Storage', 89.99, 0.1, 'https://example.com/images/samsung_ssd.jpg'),
('Garnier Hair Mask', 4.2, 65, 'Health and Beauty', 'Hair Care', 9.99, 0.05, 'https://example.com/images/garnier_mask.jpg'),
('Everlast Punching Bag', 4.3, 60, 'Sporting Goods', 'Fitness', 69.99, 0, 'https://example.com/images/everlast_punchingbag.jpg'),
('Graco Car Seat', 4.5, 85, 'Baby Products', 'Safety', 129.99, 0.1, 'https://example.com/images/graco_carseat.jpg'),
('Corsair Gaming PC', 4.7, 120, 'Gaming', 'Desktops', 1499.99, 0.1, 'https://example.com/images/corsair_pc.jpg'),
('Target Wall Art', 4.1, 50, 'Home & Office', 'Decor', 39.99, 0.15, 'https://example.com/images/target_wallart.jpg'),
('Gatorade Sports Drink', 4.2, 55, 'Supermarket', 'Beverages', 6.99, 0, 'https://example.com/images/gatorade.jpg'),
('Sony Wireless Earbuds', 4.6, 110, 'Electronics', 'Audio', 99.99, 0.1, 'https://example.com/images/sony_earbuds.jpg'),
('Old Navy Jeans', 4.0, 70, 'Fashion', 'Women''s Clothing', 29.99, 0.2, 'https://example.com/images/oldnavy_jeans.jpg'),
('Oster Toaster', 4.3, 65, 'Appliances', 'Kitchen Appliances', 29.99, 0, 'https://example.com/images/oster_toaster.jpg'),
('Intel Processor', 4.5, 90, 'Computing', 'Components', 299.99, 0.1, 'https://example.com/images/intel_processor.jpg'),
('Aveeno Lotion', 4.4, 75, 'Health and Beauty', 'Skincare', 10.99, 0.05, 'https://example.com/images/aveeno_lotion.jpg'),
('Schwinn Bike', 4.3, 60, 'Sporting Goods', 'Fitness', 249.99, 0.15, 'https://example.com/images/schwinn_bike.jpg'),
('Fisher-Price Toy', 4.2, 55, 'Baby Products', 'Toys', 19.99, 0, 'https://example.com/images/fisherprice_toy.jpg'),
('Thrustmaster Joystick', 4.5, 80, 'Gaming', 'Accessories', 69.99, 0.1, 'https://example.com/images/thrustmaster_joystick.jpg'),
('Ikea Bed Frame', 4.2, 50, 'Home & Office', 'Furniture', 199.99, 0.15, 'https://example.com/images/ikea_bed.jpg'),
('Tropicana Orange Juice', 4.1, 45, 'Supermarket', 'Beverages', 3.99, 0, 'https://example.com/images/tropicana_juice.jpg'),
('GoPro Action Camera', 4.6, 120, 'Electronics', 'Cameras', 299.99, 0.1, 'https://example.com/images/gopro_camera.jpg'),
('Banana Republic Shirt', 4.3, 70, 'Fashion', 'Men''s Clothing', 49.99, 0.15, 'https://example.com/images/bananarepublic_shirt.jpg'),
('DeLonghi Espresso Machine', 4.5, 100, 'Appliances', 'Kitchen Appliances', 199.99, 0, 'https://example.com/images/delonghi_espresso.jpg'),
('Western Digital HDD', 4.4, 85, 'Computing', 'Storage', 119.99, 0.1, 'https://example.com/images/wd_hdd.jpg'),
('Burt''s Bees Lip Balm', 4.2, 60, 'Health and Beauty', 'Personal Care', 3.99, 0, 'https://example.com/images/burtsbees_lipbalm.jpg'),
('Wilson Tennis Racket', 4.3, 65, 'Sporting Goods', 'Sports Equipment', 59.99, 0.1, 'https://example.com/images/wilson_tennis.jpg'),
('Evenflo Stroller', 4.4, 75, 'Baby Products', 'Strollers', 149.99, 0, 'https://example.com/images/evenflo_stroller.jpg'),
('ASTRO Gaming Headset', 4.6, 100, 'Gaming', 'Accessories', 129.99, 0.1, 'https://example.com/images/astro_headset.jpg'),
('Roomba Vacuum', 4.5, 110, 'Appliances', 'Cleaning', 349.99, 0.15, 'https://example.com/images/roomba_vacuum.jpg'),
('Pringles Chips', 4.0, 50, 'Supermarket', 'Snacks', 2.99, 0, 'https://example.com/images/pringles.jpg'),
('Anker Power Bank', 4.5, 95, 'Electronics', 'Accessories', 39.99, 0.1, 'https://example.com/images/anker_powerbank.jpg'),
('Calvin Klein Underwear', 4.2, 70, 'Fashion', 'Men''s Clothing', 24.99, 0.2, 'https://example.com/images/calvinklein_underwear.jpg'),
('Black & Decker Iron', 4.3, 65, 'Appliances', 'Home Appliances', 29.99, 0, 'https://example.com/images/blackdecker_iron.jpg'),
('NVIDIA Graphics Card', 4.7, 130, 'Computing', 'Components', 499.99, 0.1, 'https://example.com/images/nvidia_gpu.jpg'),
('La Roche-Posay Sunscreen', 4.4, 80, 'Health and Beauty', 'Skincare', 19.99, 0.05, 'https://example.com/images/larocheposay_sunscreen.jpg'),
('Callaway Golf Clubs', 4.3, 60, 'Sporting Goods', 'Sports Equipment', 299.99, 0.15, 'https://example.com/images/callaway_golfclubs.jpg'),
('Chicco High Chair', 4.5, 75, 'Baby Products', 'Feeding', 129.99, 0, 'https://example.com/images/chicco_highchair.jpg'),
('Logitech Webcam', 4.4, 90, 'Gaming', 'Accessories', 59.99, 0.1, 'https://example.com/images/logitech_webcam.jpg'),
('Williams Sonoma Cookware', 4.3, 55, 'Home & Office', 'Kitchenware', 149.99, 0.15, 'https://example.com/images/williamssonoma_cookware.jpg'),
('Oreo Cookies', 4.2, 60, 'Supermarket', 'Snacks', 3.99, 0, 'https://example.com/images/oreo_cookies.jpg'),
('Fitbit Fitness Tracker', 4.5, 100, 'Electronics', 'Wearables', 99.99, 0.1, 'https://example.com/images/fitbit_tracker.jpg'),
('ASOS Blazer', 4.1, 65, 'Fashion', 'Women''s Clothing', 69.99, 0.2, 'https://example.com/images/asos_blazer.jpg'),
('Keurig Coffee Maker', 4.6, 110, 'Appliances', 'Kitchen Appliances', 129.99, 0, 'https://example.com/images/keurig_coffee.jpg'),
('Seagate External Drive', 4.4, 85, 'Computing', 'Storage', 79.99, 0.1, 'https://example.com/images/seagate_drive.jpg'),
('Cetaphil Cleanser', 4.3, 70, 'Health and Beauty', 'Skincare', 11.99, 0.05, 'https://example.com/images/cetaphil_cleanser.jpg'),
('Bowflex Treadmill', 4.5, 80, 'Sporting Goods', 'Fitness', 999.99, 0.15, 'https://example.com/images/bowflex_treadmill.jpg'),
('Medela Breast Pump', 4.6, 90, 'Baby Products', 'Feeding', 199.99, 0, 'https://example.com/images/medela_pump.jpg'),
('Elgato Capture Card', 4.7, 100, 'Gaming', 'Accessories', 149.99, 0.1, 'https://example.com/images/elgato_capture.jpg'),
('Restoration Hardware Mirror', 4.2, 50, 'Home & Office', 'Decor', 249.99, 0.15, 'https://example.com/images/restoration_mirror.jpg'),
('Cheetos Snacks', 4.1, 55, 'Supermarket', 'Snacks', 3.49, 0, 'https://example.com/images/cheetos.jpg'),
('Bose Soundbar', 4.6, 120, 'Electronics', 'Audio', 399.99, 0.1, 'https://example.com/images/bose_soundbar.jpg'),
('Nordstrom Scarf', 4.3, 60, 'Fashion', 'Accessories', 29.99, 0.2, 'https://example.com/images/nordstrom_scarf.jpg'),
('Shark Steam Mop', 4.4, 75, 'Appliances', 'Cleaning', 69.99, 0, 'https://example.com/images/shark_mop.jpg'),
('AMD Ryzen Processor', 4.7, 110, 'Computing', 'Components', 349.99, 0.1, 'https://example.com/images/amd_ryzen.jpg'),
('Eucerin Cream', 4.3, 65, 'Health and Beauty', 'Skincare', 14.99, 0.05, 'https://example.com/images/eucerin_cream.jpg'),
('TaylorMade Golf Bag', 4.4, 70, 'Sporting Goods', 'Accessories', 149.99, 0.1, 'https://example.com/images/taylormade_golfbag.jpg'),
('Britax Car Seat', 4.5, 80, 'Baby Products', 'Safety', 199.99, 0, 'https://example.com/images/britax_carseat.jpg'),
('Razer Gaming Chair', 4.6, 90, 'Gaming', 'Furniture', 399.99, 0.1, 'https://example.com/images/razer_chair.jpg'),
('Anthropologie Vase', 4.2, 50, 'Home & Office', 'Decor', 49.99, 0.15, 'https://example.com/images/anthropologie_vase.jpg'),
('Lay''s Chips', 4.1, 55, 'Supermarket', 'Snacks', 3.29, 0, 'https://example.com/images/lays_chips.jpg'),
('Garmin Smartwatch', 4.5, 100, 'Electronics', 'Wearables', 199.99, 0.1, 'https://example.com/images/garmin_smartwatch.jpg'),
('Express Dress Shirt', 4.3, 65, 'Fashion', 'Men''s Clothing', 59.99, 0.2, 'https://example.com/images/express_shirt.jpg'),
('Hoover Carpet Cleaner', 4.4, 70, 'Appliances', 'Cleaning', 149.99, 0, 'https://example.com/images/hoover_cleaner.jpg'),
('Kingston USB Drive', 4.3, 80, 'Computing', 'Storage', 19.99, 0.1, 'https://example.com/images/kingston_usb.jpg'),
('Vichy Face Serum', 4.4, 75, 'Health and Beauty', 'Skincare', 34.99, 0.05, 'https://example.com/images/vichy_serum.jpg'),
('Yeti Cooler', 4.6, 85, 'Sporting Goods', 'Outdoor', 299.99, 0, 'https://example.com/images/yeti_cooler.jpg'),
('Carter''s Baby Onesie', 4.3, 60, 'Baby Products', 'Clothing', 9.99, 0.1, 'https://example.com/images/carters_onesie.jpg'),
('Cooler Master PC Case', 4.5, 90, 'Gaming', 'Components', 89.99, 0.1, 'https://example.com/images/coolermaster_case.jpg'),
('Crate & Barrel Curtains', 4.2, 50, 'Home & Office', 'Decor', 79.99, 0.15, 'https://example.com/images/crate_barrel_curtains.jpg'),
('Doritos Snacks', 4.1, 55, 'Supermarket', 'Snacks', 3.49, 0, 'https://example.com/images/doritos.jpg');

-- Query to view all products
SELECT * FROM products;